# .github/workflows/monitor-docker-build-usage.yml
name: Detect Docker Build Action Usage

on:
  pull_request:
    paths:
      - '.github/workflows/main.yml'

jobs:
  detect-docker-build-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Check for 'docker/build-push-action@v6'
        run: |
          if grep -qE '^\s*-\s*uses:\s*docker/build-push-action@v6\s*$' .github/workflows/main.yml; then
            echo "::error title=Docker Build Action Detected::'docker/build-push-action@v6' found in .github/workflows/main.yml"
            exit 1
          fi
