# .github/workflows/monitor-docker-build-usage.yml
name: Detect Docker Build Action Usage

on:
  pull_request:
    paths:
      - '.github/workflows/main.yml'

jobs:
  detect-docker-build-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   
          
      - name: Detect Docker usage in workflows
        id: docker-check
        continue-on-error: true
        run: |
          if grep -iE '\bdocker\s+push\b|docker/build-push-action' .github/workflows/*.yml | grep -viE '^\s*#'; then
            exit 1
          fi
          
      - uses: GrantBirki/git-diff-action@v2.8.1
        if: steps.docker-check.outcome == 'failure'
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          file_output_only: "true"
          search_path: '**/*.yml'

      # Print the diff in JSON format
      - name: print json diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: jq . "$DIFF"      
